version: '3.4'

x-base: &base
  volumes:
  - type: bind
    source: ../dist
    target: /dist
  - type: bind
    source: ../script
    target: /script
  privileged: true
x-environment: &env
  _DIST_DIR: /dist/centos
  _BUILD_PATH: /snort3/snort3
  _LD_LIBRARY_PATH: /usr/local/lib
  _PKG_CONFIG_PATH: /snort3/snort3/lib64/pkgconfig
  _PKG_FILENAME: snort3.spec
  _PKG_BUILD_ROOT: /root/rpmbuild
  _TARGET_LIBRARY_PATH: /usr/lib64

services:

  centos8-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/centos8-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: centos:8
        _DIST_NAME: el8
        <<: *env
    <<: *base
  
  centos8-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/centos8-install:latest
    build: 
      context: ./install
      args:
        OS_VERSION: centos:8
        _DIST_NAME: el8
        <<: *env
    <<: *base
