version: '3.4'

x-base: &base
  volumes:
  - type: bind
    source: ../dist
    target: /dist
  - type: bind
    source: ../script
    target: /script
  privileged: true
x-environment: &env
  DIST_DIR: /dist/centos
  PKG_BUILD_ROOT: /root/rpmbuild
  TARGET_LIBRARY_PATH: /usr/lib64

services:

  centos8-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/centos8-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: centos:8
    <<: *base
    environment: 
      <<: *env
  
  centos8-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/centos8-install:latest
    depends_on: 
    - centos8-build
    build: 
      context: ./install
      args:
        OS_VERSION: centos:8
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: el8
