version: '3.2'

services:

  leap15.0-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/leap15.0-build:latest
    build: 
      context: ./opensuse/build
      args:
        OS_VERSION: opensuse/leap:15.0
    environment:
      OPENSUSE_VERSION: leap-15.0
    volumes:
    - type: bind
      source: ./dist
      target: /dist
    privileged: true
  leap15.0-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/leap15.0-install:latest
    depends_on: 
    - leap15.0-build
    build: 
      context: ./opensuse/install
      args:
        OS_VERSION: opensuse/leap:15.0
    environment:
      OPENSUSE_VERSION: leap-15.0
    volumes:
    - type: bind
      source: ./dist
      target: /dist
    privileged: true

  leap15.1-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/leap15.1-build:latest
    build: 
      context: ./opensuse/build
      args:
        OS_VERSION: opensuse/leap:15.1
    environment:
      OPENSUSE_VERSION: leap-15.1
    volumes:
    - type: bind
      source: ./dist
      target: /dist
    privileged: true
  leap15.1-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/leap15.1-install:latest
    depends_on: 
    - leap15.1-build
    build: 
      context: ./opensuse/install
      args:
        OS_VERSION: opensuse/leap:15.1
    environment:
      OPENSUSE_VERSION: leap-15.1
    volumes:
    - type: bind
      source: ./dist
      target: /dist
    privileged: true

  fc30-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc30-build:latest
    build: 
      context: ./fedora/build
      args:
        OS_VERSION: fedora:30
    volumes:
    - type: bind
      source: ./dist
      target: /dist
    privileged: true
  fc30-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc30-install:latest
    depends_on: 
    - fc30-build
    build: 
      context: ./fedora/install
      args:
        OS_VERSION: fedora:30
    environment:
      FEDORA_VERSION: 30
    volumes:
    - type: bind
      source: ./dist
      target: /dist
    privileged: true

  fc31-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc31-build:latest
    build: 
      context: ./fedora/build
      args:
        OS_VERSION: fedora:31
    volumes:
    - type: bind
      source: ./dist
      target: /dist
    privileged: true
  fc31-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc31-install:latest
    depends_on: 
    - fc31-build
    build: 
      context: ./fedora/install
      args:
        OS_VERSION: fedora:31
    environment:
      FEDORA_VERSION: 31
    volumes:
    - type: bind
      source: ./dist
      target: /dist
    privileged: true
