version: '3.4'

x-base: &base
  volumes:
  - type: bind
    source: ../dist
    target: /dist
  privileged: true
x-environment: &env
  DIST_DIR: /dist/opensuse
  PKG_BUILD_ROOT: /usr/src/packages
  TARGET_LIBRARY_PATH: /usr/lib64

services:

  leap15.0-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/leap15.0-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: opensuse/leap:15.0
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: leap15.0
  
  leap15.0-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/leap15.0-install:latest
    depends_on: 
    - leap15.0-build
    build: 
      context: ./install
      args:
        OS_VERSION: opensuse/leap:15.0
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: leap15.0

  leap15.1-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/leap15.1-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: opensuse/leap:15.1
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: leap15.1
  
  leap15.1-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/leap15.1-install:latest
    depends_on: 
    - leap15.1-build
    build: 
      context: ./install
      args:
        OS_VERSION: opensuse/leap:15.1
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: leap15.1
