version: '3.4'

x-base: &base
  volumes:
  - type: bind
    source: ../dist
    target: /dist
  - type: bind
    source: ../script
    target: /script
  privileged: true
x-environment: &env
  _DIST_DIR: /dist/opensuse
  _BUILD_PATH: /snort3/snort3
  _LD_LIBRARY_PATH: /usr/local/lib
  _PKG_CONFIG_PATH: /snort3/snort3/lib64/pkgconfig
  _PKG_FILENAME: snort3.spec
  _PKG_BUILD_ROOT: /usr/src/packages
  _TARGET_LIBRARY_PATH: /usr/lib64

services:

  leap15.0-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/leap15.0-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: opensuse/leap:15.0
        _DIST_NAME: leap15.0
        <<: *env
    <<: *base
  
  leap15.0-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/leap15.0-install:latest
    build: 
      context: ./install
      args:
        OS_VERSION: opensuse/leap:15.0
        _DIST_NAME: leap15.0
        <<: *env
    <<: *base

  leap15.1-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/leap15.1-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: opensuse/leap:15.1
        _DIST_NAME: leap15.1
        <<: *env
    <<: *base
  
  leap15.1-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/leap15.1-install:latest
    build: 
      context: ./install
      args:
        OS_VERSION: opensuse/leap:15.1
        _DIST_NAME: leap15.1
        <<: *env
    <<: *base
