version: '3.4'

x-base: &base
  volumes:
  - type: bind
    source: ../dist
    target: /dist
  privileged: true
x-environment: &env
  DIST_DIR: /dist/ubuntu
  PKG_BUILD_ROOT: /snort3-0.1-1
  TARGET_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu

services:

  bionic-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/bionic-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: ubuntu:bionic
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: ubuntu-bionic
  
  bionic-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/bionic-install:latest
    depends_on: 
    - bionic-build
    build: 
      context: ./install
      args:
        OS_VERSION: ubuntu:bionic
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: ubuntu-bionic

  eoan-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/eoan-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: ubuntu:eoan
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: ubuntu-eoan
  
  eoan-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/eoan-install:latest
    depends_on: 
    - eoan-build
    build: 
      context: ./install
      args:
        OS_VERSION: ubuntu:eoan
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: ubuntu-eoan
