version: '3.4'

x-base: &base
  volumes:
  - type: bind
    source: ../dist
    target: /dist
  privileged: true
x-environment: &env
  DIST_DIR: /dist/fedora
  PKG_BUILD_ROOT: /root/rpmbuild
  TARGET_LIBRARY_PATH: /usr/lib64

services:

  fc30-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc30-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: fedora:30
    <<: *base
    environment: 
      <<: *env
  
  fc30-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc30-install:latest
    depends_on: 
    - fc30-build
    build: 
      context: ./install
      args:
        OS_VERSION: fedora:30
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: fc30

  fc31-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc31-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: fedora:31
    <<: *base
    environment: 
      <<: *env
  
  fc31-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc31-install:latest
    depends_on: 
    - fc31-build
    build: 
      context: ./install
      args:
        OS_VERSION: fedora:31
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: fc31
