version: '3.4'

x-base: &base
  volumes:
  - type: bind
    source: ../dist
    target: /dist
  - type: bind
    source: ../script
    target: /script
  privileged: true
x-environment: &env
  _DIST_DIR: /dist/fedora
  _BUILD_PATH: /snort3/snort3
  _LD_LIBRARY_PATH: /usr/local/lib
  _PKG_CONFIG_PATH: /snort3/snort3/lib64/pkgconfig
  _PKG_FILENAME: snort3.spec
  _PKG_BUILD_ROOT: /root/rpmbuild
  _TARGET_LIBRARY_PATH: /usr/lib64

services:

  fc30-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc30-build:latest
    build:
      context: ./build
      args:
        OS_VERSION: fedora:30
        _DIST_NAME: fc30
        <<: *env
    <<: *base

  fc30-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc30-install:latest
    build:
      context: ./install
      args:
        OS_VERSION: fedora:30
        _DIST_NAME: fc30
        <<: *env
    <<: *base

  fc31-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc31-build:latest
    build:
      context: ./build
      args:
        OS_VERSION: fedora:31
        _DIST_NAME: fc31
        <<: *env
    <<: *base

  fc31-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc31-install:latest
    build:
      context: ./install
      args:
        OS_VERSION: fedora:31
        _DIST_NAME: fc31
        <<: *env
    <<: *base
