version: '3.2'

services:

  fc30-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc30-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: fedora:30
    environment:
      DIST_DIR: /dist/fedora
    volumes:
    - type: bind
      source: ../dist
      target: /dist
    privileged: true
  
  fc30-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc30-install:latest
    depends_on: 
    - fc30-build
    build: 
      context: ./install
      args:
        OS_VERSION: fedora:30
    environment:
      FEDORA_VERSION: 30
      DIST_DIR: /dist/fedora
    volumes:
    - type: bind
      source: ../dist
      target: /dist
    privileged: true

  fc31-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc31-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: fedora:31
    environment:
      DIST_DIR: /dist/fedora
    volumes:
    - type: bind
      source: ../dist
      target: /dist
    privileged: true
  
  fc31-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc31-install:latest
    depends_on: 
    - fc31-build
    build: 
      context: ./install
      args:
        OS_VERSION: fedora:31
    environment:
      FEDORA_VERSION: 31
      DIST_DIR: /dist/fedora
    volumes:
    - type: bind
      source: ../dist
      target: /dist
    privileged: true
