version: '3.4'

x-base: &base
  volumes:
  - type: bind
    source: ../dist
    target: /dist
  - type: bind
    source: ../script
    target: /script
  privileged: true
x-environment: &env
  DIST_DIR: /dist/fedora
  BUILD_PATH: /snort3/snort3
  LD_LIBRARY_PATH: /usr/local/lib
  PKG_CONFIG_PATH: ${BUILD_PATH}/lib64/pkgconfig
  PKG_BUILD_ROOT: /root/rpmbuild
  TARGET_LIBRARY_PATH: /usr/lib64

services:

  fc30-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc30-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: fedora:30
    <<: *base
    environment: 
      <<: *env
  
  fc30-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc30-install:latest
    build: 
      context: ./install
      args:
        OS_VERSION: fedora:30
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: fc30

  fc31-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc31-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: fedora:31
    <<: *base
    environment: 
      <<: *env
  
  fc31-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/fc31-install:latest
    build: 
      context: ./install
      args:
        OS_VERSION: fedora:31
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: fc31
