version: '3.2'

services:

  stretch-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/raspbian-stretch-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: debian:stretch
    environment:
      DIST_NAME: raspbian-stretch
      DIST_DIR: /dist/raspbian
      PKG_BUILD_ROOT: /snort3-0.1-1
      LD_LIBRARY_PATH: /usr/local/lib
      TARGET_LIBRARY_PATH: /usr/lib/arm-linux-gnueabihf
    volumes:
    - type: bind
      source: ../dist
      target: /dist
    privileged: true
  
  stretch-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/raspbian-stretch-install:latest
    depends_on: 
    - stretch-build
    build: 
      context: ./install
      args:
        OS_VERSION: debian:stretch
    environment:
      DEBIAN_VERSION: raspbian-stretch
      DIST_DIR: /dist/raspbian
    volumes:
    - type: bind
      source: ../dist
      target: /dist
    privileged: true

  buster-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/raspbian-buster-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: debian:buster
    environment:
      DEBIAN_VERSION: raspbian-buster
      DIST_DIR: /dist/raspbian
    volumes:
    - type: bind
      source: ../dist
      target: /dist
    privileged: true
  
  buster-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/raspbian-buster-install:latest
    depends_on: 
    - buster-build
    build: 
      context: ./install
      args:
        OS_VERSION: debian:buster
    environment:
      DEBIAN_VERSION: raspbian-buster
      DIST_DIR: /dist/raspbian
    volumes:
    - type: bind
      source: ../dist
      target: /dist
    privileged: true
