version: '3.4'

x-base: &base
  volumes:
  - type: bind
    source: ../dist
    target: /dist
  - type: bind
    source: ../script
    target: /script
  privileged: true
x-environment: &env
  DIST_DIR: /dist/raspbian
  PKG_BUILD_ROOT: /snort3-0.1-1
  TARGET_LIBRARY_PATH: /usr/lib/arm-linux-gnueabihf

services:

  stretch-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/raspbian-stretch-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: debian:stretch
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: raspbian-stretch
  
  stretch-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/raspbian-stretch-install:latest
    depends_on: 
    - stretch-build
    build: 
      context: ./install
      args:
        OS_VERSION: debian:stretch
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: raspbian-stretch

  buster-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/raspbian-buster-build:latest
    build: 
      context: ./build
      args:
        OS_VERSION: debian:buster
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: raspbian-buster
  
  buster-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/raspbian-buster-install:latest
    depends_on: 
    - buster-build
    build: 
      context: ./install
      args:
        OS_VERSION: debian:buster
    <<: *base
    environment: 
      <<: *env
      DIST_NAME: raspbian-buster
