version: '3.4'

x-base: &base
  volumes:
  - type: bind
    source: ../dist
    target: /dist
  privileged: true
x-environment: &env
  _DIST_DIR: /dist/raspbian
  _BUILD_PATH: /snort3/snort3
  _LD_LIBRARY_PATH: /usr/local/lib
  _PKG_CONFIG_PATH: /snort3/snort3/lib/pkgconfig
  _PKG_FILENAME: control
  _PKG_BUILD_ROOT: /snort3-0.1-1
  _TARGET_LIBRARY_PATH: /usr/lib/arm-linux-gnueabihf

services:

  stretch-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/raspbian-stretch-build:latest
    build:
      context: ./build
      args:
        OS_VERSION: debian:stretch
        _DIST_NAME: raspbian-stretch
        <<: *env
    <<: *base

  stretch-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/raspbian-stretch-install:latest
    build:
      context: ./install
      args:
        OS_VERSION: debian:stretch
        _DIST_NAME: raspbian-stretch
        <<: *env
    <<: *base

  buster-build:
    image: docker.pkg.github.com/arturb/snort3-precompiled/raspbian-buster-build:latest
    build:
      context: ./build
      args:
        OS_VERSION: debian:buster
        _DIST_NAME: raspbian-buster
        <<: *env
    <<: *base

  buster-install:
    image: docker.pkg.github.com/arturb/snort3-precompiled/raspbian-buster-install:latest
    build:
      context: ./install
      args:
        OS_VERSION: debian:buster
        _DIST_NAME: raspbian-buster
        <<: *env
    <<: *base
